# Generated by Django 4.2.4 on 2023-08-29 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forwarding', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status_of_load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loading_status', models.CharField(choices=[('loaded', 'Załadowany'), ('waiting_for_loading', 'Oczekiwanie na załadunek')])),
                ('unloading_status', models.CharField(choices=[('unloaded', 'Rozładowany'), ('waiting_for_unloading', 'Oczekiwanie na rozładunek')])),
            ],
        ),
        migrations.CreateModel(
            name='Load_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forwarding.info_transport')),
            ],
        ),
        migrations.CreateModel(
            name='Info_of_truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.DecimalField(blank=True, decimal_places=1, max_digits=8, verbose_name='Przebieg')),
                ('fuel', models.DecimalField(blank=True, decimal_places=2, max_digits=6, verbose_name='Tankowanie')),
                ('service', models.CharField(choices=[('Yes', 'Przesmarowany'), ('No', 'Nie przesmarowany')], verbose_name='Przebieg')),
                ('description', models.TextField()),
                ('driver_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('trailer_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.trailer')),
                ('truck_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.truck')),
            ],
        ),
    ]
