# Generated by Django 4.2.4 on 2023-08-29 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firs_name',
            new_name='drive_license',
        ),
    ]
