# Generated by Django 4.2.4 on 2023-08-29 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0001_initial'),
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_of_truck',
            name='description',
            field=models.TextField(verbose_name='Uwagi'),
        ),
        migrations.AlterField(
            model_name='info_of_truck',
            name='driver_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kierowca'),
        ),
        migrations.AlterField(
            model_name='info_of_truck',
            name='service',
            field=models.CharField(choices=[('Yes', 'Przesmarowany'), ('No', 'Nie przesmarowany')], verbose_name='Serwis'),
        ),
        migrations.AlterField(
            model_name='info_of_truck',
            name='trailer_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.trailer', verbose_name='Rejestracja przyczepy'),
        ),
        migrations.AlterField(
            model_name='info_of_truck',
            name='truck_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.truck', verbose_name='Rejestracja ciężarówki'),
        ),
    ]
