# Generated by Django 4.2.4 on 2023-08-29 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trailerRegistration', models.CharField(blank=True, max_length=8, unique=True, verbose_name='Numer rejestracyjny')),
                ('trailerNumber', models.CharField(blank=True, max_length=3, unique=True, verbose_name='Numer boczny')),
                ('trailerType', models.CharField(blank=True, choices=[('standard', 'Standard'), ('mega', 'Mega')], verbose_name='Rodzaj naczepy')),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truckRegistration', models.CharField(blank=True, max_length=8, unique=True, verbose_name='Numer rejestracyjny')),
                ('truckNumber', models.CharField(blank=True, max_length=3, unique=True, verbose_name='Numer boczny')),
                ('truckType', models.CharField(blank=True, choices=[('standard', 'Standard'), ('mega', 'Mega')], verbose_name='Rodzaj auta')),
                ('truckFuelTank', models.CharField(blank=True, max_length=4, verbose_name='Zbiornik paliwa')),
                ('truckHP', models.CharField(blank=True, max_length=3, verbose_name='Moc')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, verbose_name='Imię')),
                ('surname', models.CharField(blank=True, max_length=64, verbose_name='Nazwisko')),
            ],
        ),
        migrations.CreateModel(
            name='TruckTrailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trailerSet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.trailer')),
                ('truckSet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.truck')),
            ],
        ),
        migrations.CreateModel(
            name='TruckSetToWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.workerdriver')),
                ('truckSet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.trucktrailer')),
            ],
        ),
    ]
